# Generated by Django 3.0.7 on 2020-06-11 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='ann_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预案公告日'),
        ),
        migrations.AlterField(
            model_name='share',
            name='base_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='基准日'),
        ),
        migrations.AlterField(
            model_name='share',
            name='div_listdate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='红股上市日'),
        ),
        migrations.AlterField(
            model_name='share',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分红年度'),
        ),
        migrations.AlterField(
            model_name='share',
            name='ex_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='除权登记日'),
        ),
        migrations.AlterField(
            model_name='share',
            name='imp_ann_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实施公告日'),
        ),
        migrations.AlterField(
            model_name='share',
            name='pay_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='派息日'),
        ),
        migrations.AlterField(
            model_name='share',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='股权登记日'),
        ),
    ]
