# Generated by Django 3.0.7 on 2020-06-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20200611_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='base_share',
            field=models.FloatField(blank=True, null=True, verbose_name='基准股本（万）'),
        ),
        migrations.AlterField(
            model_name='share',
            name='cash_div',
            field=models.FloatField(blank=True, null=True, verbose_name='每股分红（税后）'),
        ),
        migrations.AlterField(
            model_name='share',
            name='cash_div_tax',
            field=models.FloatField(blank=True, null=True, verbose_name='每股分红（税前）'),
        ),
        migrations.AlterField(
            model_name='share',
            name='div_proc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='实施进度'),
        ),
        migrations.AlterField(
            model_name='share',
            name='stk_bo_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='每股送转比例'),
        ),
        migrations.AlterField(
            model_name='share',
            name='stk_co_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='每股转增比例'),
        ),
        migrations.AlterField(
            model_name='share',
            name='stk_div',
            field=models.FloatField(blank=True, null=True, verbose_name='每股送转'),
        ),
    ]
